# Páginas para programar python

1. www.mybinder.org
2. www.kaggle.com
3. www.jupyter.org/try
4. `github jobish` https://mybinder.org/v2/gh/jobish03/jobish03-Visualizacion_de_datos_para_la_toma_de_decisiones/main?filepath=welcome_binder.ipynb

Los paquetes hay que incluir en el archivo `requirements.txt`

In [ ]:
#pip install seaborn

In [ ]:
#pip install sklearn

In [18]:
pip install statsmodels

Collecting statsmodels
  Downloading statsmodels-0.13.1-cp37-cp37m-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (9.8 MB)
     |████████████████████████████████| 9.8 MB 4.6 MB/s
Requirement already satisfied: pandas>=0.25 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.0.4)
Requirement already satisfied: numpy>=1.17 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.18.5)
Requirement already satisfied: scipy>=1.3 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from statsmodels) (1.4.1)
Collecting patsy>=0.5.2
  Downloading patsy-0.5.2-py2.py3-none-any.whl (233 kB)
     |████████████████████████████████| 233 kB 43.7 MB/s
Requirement already satisfied: pytz>=2017.2 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.25->statsmodels) (2020.1)
Requirement already satisfied: python-dateutil>=2.6.1 in /srv/conda/envs/notebook/lib/python3.7/site-packages (from pandas>=0.25->statsmodels) (2.8.1)
Requirement already satisfied: six in /srv/conda/envs/notebook/lib/python3.7/site-packages (from patsy>=0.5.2->statsmodels) (1.16.0)
Installing collected packages: patsy, statsmodels
Successfully installed patsy-0.5.2 statsmodels-0.13.1
Note: you may need to restart the kernel to use updated packages.

In [19]:
import pandas as pd
import numpy as np
import matplotlib as mpl
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn import linear_model
import statsmodels.api as sm

In [20]:
%ls datasets

 adult.csv                   Cartwheeldata.csv   mic.xlsx
 airline_data.csv            census.csv          movies.csv
 antropometria00.csv         coches.csv          nhanes_2015_2016.csv
 antropometria-dataset.csv   cwurData.csv        pokemon.csv
 athletes.csv                data.csv            sample_pivot.csv
 athletes_games.csv          happiness2015.csv  'Student performance.xlsx'
 Book3.csv                   headbrain.csv       tips.csv
 Canada.xlsx                 mic2.xlsx           weight-height.csv

In [21]:
df = pd.read_csv('datasets/antropometria-dataset.csv')
df

,folio,intp,entidad,desc_ent,sexo,edad,meses,peso,ropa,talla,...,hpresion,tbrazo,htension,PrimaryLast,code_upm,est_dis,est_urb,est_marg,pondef,est_var
0,210295,2,21,PUEBLA,2,38,8,73.70,2,146.40,...,16:30,2,16:35,1,R2101,5,3,1,3470.002176,215
1,101655,3,10,DURANGO,2,11,11,35.65,2,145.10,...,15:25,3,15:25,1,M1041,1,1,1,417.946672,101
2,10287,6,1,AGUASCALIENTES,2,18,8,54.80,1,162.00,...,9:40,1,9:40,1,M0108,5,3,1,472.980811,15
3,91526,4,9,DISTRITO FEDERAL,1,10,8,33.40,2,146.50,...,7:40,3,7:45,1,M0931,4,3,2,1832.581391,94
4,210939,3,21,PUEBLA,2,19,3,97.95,2,161.00,...,6:00,2,6:00,1,M2123,5,3,1,7622.066564,215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18635,300116,2,30,VERACRUZ DE IGNACIO DE LA LLAVE,2,73,11,75.80,1,141.15,...,18:00,1,18:05,1,R3002,5,3,1,7615.607749,305
18636,40253,1,4,CAMPECHE,2,75,0,69.40,1,144.80,...,18:40,1,18:40,1,M0408,5,3,1,195.314670,45
18637,301099,1,30,VERACRUZ DE IGNACIO DE LA LLAVE,1,86,7,46.75,2,149.20,...,8:00,3,23:00,1,M3024,2,1,2,1758.912979,302
18638,250801,1,25,SINALOA,2,72,7,59.05,2,142.50,...,6:02,3,6:02,1,M2512,3,2,1,2354.581350,253
18639,11786,2,1,AGUASCALIENTES,2,71,8,80.00,2,150.65,...,13:50,3,13:00,1,M0143,2,1,2,591.847039,12

In [22]:
df.columns

Index(['folio', 'intp', 'entidad', 'desc_ent', 'sexo', 'edad', 'meses', 'peso',
       'ropa', 'talla', 'emb', 'temb', 'cintura', 'cadera', 'sistol',
       'diastol', 'hpresion', 'tbrazo', 'htension', 'PrimaryLast', 'code_upm',
       'est_dis', 'est_urb', 'est_marg', 'pondef', 'est_var'],
      dtype='object')

In [23]:
modelA = sm.OLS.from_formula('cadera~peso', data = df)
resultA = modelA.fit()
y = resultA.resid
y.median()

-0.6495739811776744

In [24]:
vars = ['folio', 'intp', 'entidad', 'desc_ent', 'sexo', 'edad', 'meses', 'peso',
       'ropa', 'talla', 'emb', 'temb', 'cintura', 'cadera', 'sistol',
       'diastol', 'hpresion', 'tbrazo', 'htension', 'PrimaryLast', 'code_upm',
       'est_dis', 'est_urb', 'est_marg', 'pondef', 'est_var']
df = df[vars].dropna()
df

,folio,intp,entidad,desc_ent,sexo,edad,meses,peso,ropa,talla,...,hpresion,tbrazo,htension,PrimaryLast,code_upm,est_dis,est_urb,est_marg,pondef,est_var
0,210295,2,21,PUEBLA,2,38,8,73.70,2,146.40,...,16:30,2,16:35,1,R2101,5,3,1,3470.002176,215
1,101655,3,10,DURANGO,2,11,11,35.65,2,145.10,...,15:25,3,15:25,1,M1041,1,1,1,417.946672,101
2,10287,6,1,AGUASCALIENTES,2,18,8,54.80,1,162.00,...,9:40,1,9:40,1,M0108,5,3,1,472.980811,15
3,91526,4,9,DISTRITO FEDERAL,1,10,8,33.40,2,146.50,...,7:40,3,7:45,1,M0931,4,3,2,1832.581391,94
4,210939,3,21,PUEBLA,2,19,3,97.95,2,161.00,...,6:00,2,6:00,1,M2123,5,3,1,7622.066564,215
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18635,300116,2,30,VERACRUZ DE IGNACIO DE LA LLAVE,2,73,11,75.80,1,141.15,...,18:00,1,18:05,1,R3002,5,3,1,7615.607749,305
18636,40253,1,4,CAMPECHE,2,75,0,69.40,1,144.80,...,18:40,1,18:40,1,M0408,5,3,1,195.314670,45
18637,301099,1,30,VERACRUZ DE IGNACIO DE LA LLAVE,1,86,7,46.75,2,149.20,...,8:00,3,23:00,1,M3024,2,1,2,1758.912979,302
18638,250801,1,25,SINALOA,2,72,7,59.05,2,142.50,...,6:02,3,6:02,1,M2512,3,2,1,2354.581350,253
18639,11786,2,1,AGUASCALIENTES,2,71,8,80.00,2,150.65,...,13:50,3,13:00,1,M0143,2,1,2,591.847039,12

In [26]:
df.corr()

,folio,intp,entidad,sexo,edad,meses,peso,ropa,talla,cintura,cadera,sistol,diastol,PrimaryLast,est_dis,est_urb,est_marg,pondef,est_var
folio,1.000000,-0.018285,0.999979,0.011818,0.027533,0.015936,-0.045357,0.011602,-0.074838,-0.026543,-0.032166,0.003544,-0.019667,NaN,-0.098056,-0.111854,0.004909,0.008397,0.999845
intp,-0.018285,1.000000,-0.018354,0.048520,-0.643283,-0.006917,-0.379398,-0.007933,-0.148824,-0.421887,-0.321075,-0.347045,-0.283804,NaN,-0.005491,-0.000499,0.017748,0.038982,-0.018478
entidad,0.999979,-0.018354,1.000000,0.011848,0.027654,0.015988,-0.045395,0.011559,-0.074842,-0.026583,-0.032198,0.003630,-0.019632,NaN,-0.098377,-0.111987,0.004491,0.008220,0.999861
sexo,0.011818,0.048520,0.011848,1.000000,0.053430,-0.000969,-0.125084,-0.001242,-0.463927,0.014791,0.169966,-0.070934,-0.048191,NaN,0.007098,0.014335,-0.020250,-0.038987,0.012015
edad,0.027533,-0.643283,0.027654,0.053430,1.000000,0.003480,0.318568,0.018035,0.017608,0.478879,0.340062,0.535053,0.344207,NaN,-0.038951,-0.023742,-0.025959,0.035903,0.027112
meses,0.015936,-0.006917,0.015988,-0.000969,0.003480,1.000000,-0.003448,0.004257,0.009250,0.000214,0.000300,0.008742,-0.005078,NaN,0.000716,0.000261,-0.001885,0.016540,0.016002
peso,-0.045357,-0.379398,-0.045395,-0.125084,0.318568,-0.003448,1.000000,0.005194,0.558683,0.791677,0.777061,0.355847,0.361438,NaN,0.086622,0.112806,-0.107396,0.086720,-0.043901
ropa,0.011602,-0.007933,0.011559,-0.001242,0.018035,0.004257,0.005194,1.000000,-0.006733,0.007701,0.003628,0.056620,-0.010427,NaN,-0.025475,-0.038039,0.015904,-0.053166,0.011057
talla,-0.074838,-0.148824,-0.074842,-0.463927,0.017608,0.009250,0.558683,-0.006733,1.000000,0.245208,0.273173,0.140266,0.151905,NaN,0.083146,0.106353,-0.093317,0.096219,-0.073463
cintura,-0.026543,-0.421887,-0.026583,0.014791,0.478879,0.000214,0.791677,0.007701,0.245208,1.000000,0.863396,0.403265,0.362961,NaN,0.049018,0.071307,-0.067250,0.062563,-0.025732
cadera,-0.032166,-0.321075,-0.032198,0.169966,0.340062,0.000300,0.777061,0.003628,0.273173,0.863396,1.000000,0.307012,0.296613,NaN,0.072143,0.103383,-0.099546,0.065710,-0.030944
sistol,0.003544,-0.347045,0.003630,-0.070934,0.535053,0.008742,0.355847,0.056620,0.140266,0.403265,0.307012,1.000000,0.662332,NaN,-0.017577,-0.017656,-0.011573,0.012869,0.003389
diastol,-0.019667,-0.283804,-0.019632,-0.048191,0.344207,-0.005078,0.361438,-0.010427,0.151905,0.362961,0.296613,0.662332,1.000000,NaN,0.016023,0.023528,-0.019688,0.032570,-0.019315
PrimaryLast,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
est_dis,-0.098056,-0.005491,-0.098377,0.007098,-0.038951,0.000716,0.086622,-0.025475,0.083146,0.049018,0.072143,-0.017577,0.016023,NaN,1.000000,0.865632,-0.232361,0.127534,-0.082036
est_urb,-0.111854,-0.000499,-0.111987,0.014335,-0.023742,0.000261,0.112806,-0.038039,0.106353,0.071307,0.103383,-0.017656,0.023528,NaN,0.865632,1.000000,-0.467315,0.248500,-0.096938
est_marg,0.004909,0.017748,0.004491,-0.020250,-0.025959,-0.001885,-0.107396,0.015904,-0.093317,-0.067250,-0.099546,-0.011573,-0.019688,NaN,-0.232361,-0.467315,1.000000,-0.290688,0.000263
pondef,0.008397,0.038982,0.008220,-0.038987,0.035903,0.016540,0.086720,-0.053166,0.096219,0.062563,0.065710,0.012869,0.032570,NaN,0.127534,0.248500,-0.290688,1.000000,0.010615
est_var,0.999845,-0.018478,0.999861,0.012015,0.027112,0.016002,-0.043901,0.011057,-0.073463,-0.025732,-0.030944,0.003389,-0.019315,NaN,-0.082036,-0.096938,0.000263,0.010615,1.000000

In [27]:
modelB = sm.OLS.from_formula('diastol~sistol', data = df)
resultB = modelB.fit()
resultB.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                diastol   R-squared:                       0.439
Model:                            OLS   Adj. R-squared:                  0.439
Method:                 Least Squares   F-statistic:                 1.409e+04
Date:                Fri, 03 Dec 2021   Prob (F-statistic):               0.00
Time:                        14:26:33   Log-Likelihood:                -64272.
No. Observations:               18032   AIC:                         1.285e+05
Df Residuals:                   18030   BIC:                         1.286e+05
Df Model:                           1
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     23.9991      0.440     54.564      0.000      23.137      24.861
sistol         0.4350      0.004    118.705      0.000       0.428       0.442
==============================================================================
Omnibus:                     1016.455   Durbin-Watson:                   1.745
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3973.980
Skew:                           0.128   Prob(JB):                         0.00
Kurtosis:                       5.286   Cond. No.                         830.
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
"""

In [28]:
modelB = sm.OLS.from_formula('diastol~sistol + edad + peso + cintura', data = df)
resultB = modelB.fit()
resultB.summary()

<class 'statsmodels.iolib.summary.Summary'>
"""
                            OLS Regression Results
==============================================================================
Dep. Variable:                diastol   R-squared:                       0.458
Model:                            OLS   Adj. R-squared:                  0.458
Method:                 Least Squares   F-statistic:                     3812.
Date:                Fri, 03 Dec 2021   Prob (F-statistic):               0.00
Time:                        14:31:33   Log-Likelihood:                -63952.
No. Observations:               18032   AIC:                         1.279e+05
Df Residuals:                   18027   BIC:                         1.280e+05
Df Model:                           4
Covariance Type:            nonrobust
==============================================================================
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
Intercept     20.3297      0.520     39.089      0.000      19.310      21.349
sistol         0.4140      0.004     94.447      0.000       0.405       0.423
edad          -0.0272      0.004     -6.934      0.000      -0.035      -0.020
peso           0.0825      0.006     14.154      0.000       0.071       0.094
cintura        0.0202      0.007      3.072      0.002       0.007       0.033
==============================================================================
Omnibus:                     1031.138   Durbin-Watson:                   1.769
Prob(Omnibus):                  0.000   Jarque-Bera (JB):             3722.633
Skew:                           0.189   Prob(JB):                         0.00
Kurtosis:                       5.194   Cond. No.                     1.39e+03
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.
[2] The condition number is large, 1.39e+03. This might indicate that there are
strong multicollinearity or other numerical problems.
"""